FROM devopsfaith/krakend:2.0.5 as builder

COPY krakend.tmpl .
COPY config .

RUN FC_ENABLE=1 \
    FC_OUT=/tmp/krakend.json \
    FC_PARTIALS="/etc/krakend/partials" \
    FC_SETTINGS="/etc/krakend/settings" \
    FC_TEMPLATES="/etc/krakend/templates" \
    krakend check -d -t -c krakend.tmpl

FROM devopsfaith/krakend:2.0.5
COPY --from=builder /tmp/krakend.json .
